### ISSUE TITLE
node throwing error when using validate() function

### ISSUE THREAD

**Issue by carlosedp** [dandean/express-form#1]
When using the validate() function, node is throwing an error:

node.js:63
    throw e;
    ^
WideCharToMultiByte: The data area passed to a system call is too small.
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at Object.<anonymous> (/mnt/e/Dev/sandbox/node.js/webdownloader/test_validate.js:21:5)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at Object.runMain (node.js:522:24)
    at Array.<anonymous> (node.js:756:12)
    at EventEmitter._tickCallback (node.js:55:22)
    at node.js:773:9

My code:

server.post('/', 
        form(
            validate("download").required(),
            validate("email").required()
            ),
        function(request, response) {
....

**Comment by dandean** [comment]
That stack trace looks like the error is coming from Node, not Express Form.

Does it work when you remove this for your code?

```
form(
    validate("download").required(),
    validate("email").required()
    ),
```

**Comment by carlosedp** [comment]
Yes, works fine. I'm using node 0.2.6 and validating "by hand" with custom functions.

**Comment by dandean** [comment]
Can you post more of your code? I think that'll help me to diagnose what's going wrong.

**Comment by carlosedp** [comment]
I have the problem with the example itself:

var express = require("express");
var form = require("express-form"),
    filter = form.filter,
    validate = form.validate;

var app = express.createServer();

app.configure(function() {
  app.use(express.bodyDecoder());
  app.use(app.router);
});

app.post(

  // Route
  '/user',

  // Form filter and validation middleware
  form(
    filter("username").trim(),
    validate("username").required().is(/^[a-z]+$/),
    filter("password").trim(),
    validate("password").required().is(/^[0-9]+$/)
  ),

  // Express request-handler now receives filtered and validated data
  function(req, res){
    if (!req.form.isValid) {
      // Handle errors
      console.log(req.form.errors);

```
} else {
  // Or, use filtered form data from the form object:
  console.log("Username:", req.form.username);
  console.log("Password:", req.form.password);
}
```

  }
);

~/dev/sandbox/node.js $ node test_validator.js

node.js:63
    throw e;
    ^
WideCharToMultiByte: The data area passed to a system call is too small.
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at Object.<anonymous> (/mnt/e/Dev/sandbox/node.js/test_validator.js:21:5)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at Object.runMain (node.js:522:24)
    at Array.<anonymous> (node.js:756:12)
    at EventEmitter._tickCallback (node.js:55:22)
    at node.js:773:9

~/dev/sandbox/node.js $ node --version
v0.2.6
~/dev/sandbox/node.js $ npm ls installed
npm info it worked if it ends with ok
npm info using npm@0.2.15
npm info using node@v0.2.6
connect@0.5.6            High performance middleware framework    =creationix =tjholowaychuk active installed
ejs@0.2.1                Embedded JavaScript templates    =tjholowaychuk active installed latest remote templ
express@1.0.3            Sinatra inspired web development framework    =tjholowaychuk active installed latest
express-form@0.4.0       Form validation and data filtering for Express    =dandean active installed latest r
jade@0.6.0               Jade template engine    =tjholowaychuk active installed latest remote
mongodb@0.7.9            A node.js driver for MongoDB    =christkv active installed latest remote
npm@0.2.15               A package manager for node    =isaacs active installed remote package manager module
object-additions@0.5.0   Methods which extend the Object object.    =dandean active installed latest remote
redis-node@0.2.8         A Complete Redis Client for Node.js    =bnoguchi active installed latest remote redi
validator@0.1.6          Data validation, filtering and sanitization for node.js    =cohara87 active installe
npm ok

**Comment by dandean** [comment]
Shit, that's an errror in my documentation. Line 4 should look like this:

```
validate = form.validator;
```

**Comment by dandean** [comment]
Ok, I've fixed the example in the README. Thanks for reporting this.

**Comment by carlosedp** [comment]
Worked perfectly! Thanks!

**Comment by dandean** [comment]
No problem!
