### ISSUE TITLE
Can't filter Mongoose-style fields

### ISSUE THREAD

**Issue by drplokta** [dandean/express-form#10]
Using Mongoose as the back-end of my forms requires field names like 'user[username]', and they're not working with express-form filters.

**Comment by dandean** [comment]
Interesting. I haven't used Mongoose yet, so haven't had to deal with issues related to that project. I think the conflict is that express-form is going to expect your data to be in the format of

``` javascript
user = {
  username: "blah"
}
```

Is that not how your data is structured? Do you have any more detailed code examples of your use case?

Thanks.

**Comment by drplokta** [comment]
Instead of having fieldnames like "email" and "username", producing a form object like:

<pre>
{
  username: testuser
  email: test@invalid.test
}
</pre>


I have fields like "user[email]" and "user[username]", so that Mongoose knows that "email" and "username" are fields in the "user" collection, and it produces a form object like this:

<pre>
{
  user:
  {
    username: testuser
    email: test@invalid.test
  }
}
</pre>


The current express-form code can't cope with this multiple level form object.

I'm submitting a pull request now that patches it for this example with one additional level (but not for the generic many-level case where there might be a field like "table[subtable1[subtable2[subtable3[field]]]]").

**Comment by dandean** [comment]
This should work for you now, if you use dot-syntax.
