### ISSUE TITLE
Filter does not work on nested fields

### ISSUE THREAD

**Issue by dandean** [dandean/express-form#13]
Reported by @shamod in the comments for this issue: https://github.com/dandean/express-form/issues/4

Here are his notes:

run into this error. i have:

`input(id="name", name="user[name]", type="text", value='')` and it fails on filter 

```
form( filter( "user[name]" ).trim( ) )
```

with this error 

TypeError: Cannot call method 'replace' of undefined 

Using v0.5.3. Any idea?

**Comment by dandean** [comment]
@shamod: by v0.5.3, you mean **Node** v0.5.3 right? Just want to be clear with everything.

What version of Express are you using?

**Comment by shamod** [comment]
2.2.0

**Comment by dandean** [comment]
Thanks!

**Comment by mjadobson** [comment]
I've fixed this so you can use dot notation to get to values.

```
filter("post.author").trim()
```

which imitates more how you would access req.body than the html field names.

I've also added a few options like autoTrim, and noPassThrough.

Ended up breaking autolocals and datasources though, so I'll try and get those working again before I make a pull request.

**Comment by dandean** [comment]
Excellent -- thank you!

**Comment by dandean** [comment]
Fixed!
