### ISSUE TITLE
Incompatible with HTML5 forms

### ISSUE THREAD

**Issue by akiva** [dandean/express-form#15]
My forms using HTML5 form elements, which are not being parsed properly. For instance:

> <input type="email" id="email" name="message[sender][email]" 
>          placeholder="Please enter your e-mail address" required />

Won't work. However, if I change type="email" to type="text", everything works as expected.

This seems really odd, as you would think it would work fine. I heavily use HTML5 forms all the time.

**Comment by akiva** [comment]
Sorry, that code snippet should have read:

`<input type="email" id="email" name="message[sender][email]" placeholder="Please enter your e-mail address" required />`

**Comment by mjadobson** [comment]
Works fine for me. What versions of Express, Node.js, Express-Form, etc. are you using?

**Comment by akiva** [comment]
Updating to the latest (which npm was not doing originally for some reason) fixed it (0.6.0). Thanks!
