### ISSUE TITLE
Array validation/filtering

### ISSUE THREAD

**Issue by mjadobson** [dandean/express-form#18]
Have methods to deal with arrays themselves. eg/ arrayLength(), push(), etc.

**Comment by dandean** [comment]
``` js
field('favorites').includes('awesome');
...                excludes('lame');
...                length(3);
```

It seems like `length` could be used for both string and array values. They both have a length property, so we could just ducktype check for it:

``` js
if (typeof value.length != "undefined") {
  if (value.length != length) throw new Error(...);
}
```

Other possibly useful validators could be `includes` and `excludes`.

**Comment by dandean** [comment]
But what would `push` be used for? Seems odd to modify the array content from within the form validator.

**Comment by mjadobson** [comment]
Yeah, not sure what array methods to add. Includes/excludes look good though.

Filtering the array in form() with push, splice, shift etc. seems ok to me. It lets you put all your data transformation in one place.

Can't have .length() for both strings and arrays with the current setup, as you still want the string method around to validate each value within the array. 

``` javascript
field("users").array().arrLength(5).charLength(32).toUpper()
```

There is a danger here of making things look kinda confusing/ugly; may need to rethink how best to implement this stuff. Having "arr" prefacing all of the array methods is a bit of a mess, but I can't think of a good way to divide the array/string methods while still maintaing the fluent interface.

``` javascript
field("users").array.length(5)
field("users[]").length(32).toUpper()
```

Maybe something like that is cleaner? I dunno.

``` javascript
field("users").array.length(5).each(function (foo) {
    foo.length(32).toUpper()
})
```

Or this?

**Comment by freewil** [comment]
this is old, please reopen if still applicable
