### ISSUE TITLE
autoLocals cause TypeError

### ISSUE THREAD

**Issue by craftgear** [dandean/express-form#2]
Error in form.js at 46
TypeError: Cannot set property 'field_name' of undefined

It looks "res.options" propterty is undefiend.

update:
I forgot to write software version.
node@0.2.6
express@1.0.7
express-form@github-master

**Comment by dandean** [comment]
Ah, sorry you ran into that. I've got this fixed in my local build, but haven't pushed this yet. I'll get it up soon.

**Comment by dandean** [comment]
Fixed in this commit:

https://github.com/dandean/express-form/commit/9c497b45c7ca50b859ccfffe3a0a6ebd9ed5c913
