### ISSUE TITLE
equals broken since rewrite

### ISSUE THREAD

**Issue by wavded** [dandean/express-form#22]
I thought I had a test for this but guess not, nested properties no longer work with equals after the recent rewrite:

e.g.

``` js
form(
    form.validate('verify_password','Verify Password').equals('field::user[password]', "Passwords do not match")
)
```

**Comment by mjadobson** [comment]
This should work if you use dot notation:

``` javascript
form(
    form.validate('verify_password','Verify Password').equals('field::user.password', "Passwords do not match")
)
```

The issue here is that the regex I used to transform square-bracket to dots:

``` javascript
property = property.replace(/\[((.)*?)\]/g, ".$1"); // Convert square-bracket to dot notation.
```

..resides in the Field function, rather than in utils.getProp, so the equals method doesn't get its object-path transformed. Should be an easy fix.
