### ISSUE TITLE
Field data not passed onto the final middleware unless filtered

### ISSUE THREAD

**Issue by akiva** [dandean/express-form#24]
Hello again,

I have the same form as previously mentioned (has a due date applicable check mark and upon clicking it, a text field appears for said date). Unless I perform an empty filter() on the hidden field, it won't get passed onto the next middleware (previously this was working by doing a custom filter on the checkmark.), see code below:

Form:

`<dl>
`    <dt class="deadline">
`<label for="deadline">
`        Does your project have a planned deadline?
`</label>
`    </dt> 
`<dd class="deadline">
`      <input type="checkbox" id="deadline" name="message[deadline][applicable]" 
`          value="1" />
`</dd> 
`    <dt class="deadline_date">
`<label for="deadline_date">
`        Please enter your project&rsquo;s deadline
`</label>
`    </dt> 
`<dd class="deadline_date">
`      <input type="text" id="deadline_date" name="message[deadline][deadline]" 
`          placeholder="Project deadline" />
`</dd> 
`  </dl>

And in my form route middleware, I have 

`field("message.deadline.applicable")
`      .custom(function (value, data) {
`if (value && !data.message.deadline.deadline.trim()) {
`          throw new Error("A date must be specified if a deadline applies.");
`}
`      }),

Now, if I leave it there, it used to still pass `data.message.deadline.deadline` to the next route but now it doesn't. However, if I add this meaningless filter: 

`    field("message.deadline.deadline"),

then all is good again in the land of Akiva.

I can apply this now to get things working, but perhaps it is a bug?

**Comment by mjadobson** [comment]
This is an expected behaviour.

You should use the `passThrough: true` option if you want to access source properties without declaring them. Or simply access `req.body.message.deadline.deadline` directly.

**Comment by akiva** [comment]
Wow, this was quite a while ago... I believe it was solved (or circumvented) in some fashion, but I no longer recall, so I will close the issue.
