### ISSUE TITLE
Custom validation and required fields

### ISSUE THREAD

**Issue by JanVanRyswyck** [dandean/express-form#27]
In the runStack function, there's the following line:

// If this field is not required and it doesn't have a value, ignore error.
if (!utils.hasValue(value) && !self.__required) return;

Isn't this up to the custom function to determine if the value is required or not and when it is, it has to check for the 'requiredness' itself? Thoughts?

**Comment by freewil** [comment]
If you want to add a unit test (and implementation if you're feeling daring) I'll be glad to merge/work on this.
