### ISSUE TITLE
Documentation for required()

### ISSUE THREAD

**Issue by niftylettuce** [dandean/express-form#28]
The documentation or functionality for usage of `required()` is a bit confusing.

If you just simply want to pass a custom required message, the only way to currently do so is:

```
  form(
      filter("name").trim()
    , validate("name").required("name", "Please enter your %s, we'd love to know what it is!")
  );
```

Might you update the docs? -- I could if you'd like :)  Let me know.

**Comment by dhruv-bhatia** [comment]
I agree that this is very confusing. Currently the example in the documentation states that the `required()` function should only take a single `message` argument when in actuality you need to pass the `placeholderValue` and the desired custom `message` value.

**Comment by niftylettuce** [comment]
just use `node-validator`, it's much easier and kept up to date ;)
