### ISSUE TITLE
feature request - clientside code sharing

### ISSUE THREAD

**Issue by alanclarke** [dandean/express-form#32]
this is a really elegant solution to form validation.

another killer feature would be some way of passing the same validation logic to the browser to perform clientside validation as well as serverside.

i'm aware of browserify but not sure how this would fit in with the connect model, would need some kind of abstraction

**Comment by freewil** [comment]
Take a look at https://github.com/dandean/express-form/blob/master/test/form.test.js#L51 for an idea of how to customize the source of the input
