### ISSUE TITLE
Express-Form as Route Middleware "module"

### ISSUE THREAD

**Issue by OClement** [dandean/express-form#33]
I'm pretty new to Node and I'm not sure if it is me or a limitation of Express-Form, so bear with me please;

I want to use Express-Form to validate different form submissions, but instead of adding the logic directly in the PUT/POST Request, I would like to modularize it all.

app.js contains my routes like so:

```
var routes_users =      require('./routes/users');
app.put('/users/create', routes_users.createUser);
```

And I would like to call Express-Form like so:

```
var formValidator =     require('./formValidator');
app.put('/users/create', formValidator.validate('createUser'), routes_users.createUser);
```

formValidator.js:

```
var form        = require('express-form'),
    filter      = form.filter,
    validate    = form.validate;

function createUser(req, res, next) {
    return form(
        validate('username').required();
        ...
}

module.exports.validate = function(formName)  {

    // If anyone has a way to get rid of this switch, and directly call the function from the string, please tell me!

    switch(formName) {
        case "userCreate":
            return createUser;
        break;
    }
};
```

So, am I doing it wrong or is this a limitation of Express-Form and it cannot be used like so?
Following the method from the examples works fine.

Thanks

**Comment by mjadobson** [comment]
I do this for larger projects:

https://github.com/dandean/express-form/issues/23

It's a bit ugly to set up, but is pretty clean route-wise.

**Comment by OClement** [comment]
Thanks for the reply
Some more research led me to Express-Validator (Node-Validator) which better suits my needs

I guess the issue could still be left open for others to add their thoughts and maybe the dev would want to "solve" it or give his position on this

**Comment by freewil** [comment]
dup of #23
