### ISSUE TITLE
express-forms incompatible with latest express (3.0.0beta5+)

### ISSUE THREAD

**Issue by mwawrusch** [dandean/express-form#37]
I receive the following error:

TypeError: Object # has no method 'local'
    at /Users/mwawrusch/Documents/scottyapp-project/scotty-io/node_modules/express-form/lib/form.js:32:15

which is because in express 3.0 res.locals is defined as a function, but res.local does not exist. See here: https://github.com/visionmedia/express/blob/master/lib/utils.js#L18

One way to fix it seems to check for the existence of res.local, although this is not a perfect solution.

**Comment by mwawrusch** [comment]
Here is some fix (middleware) that helps for the time being:

```
expressFormsFix = () ->
  fn = (req,res,next) ->
    res.local = (key,val) ->
      res.locals[key] = val
    next()
  fn
```

**Comment by elyran** [comment]
Anyone going to fix this?

I'm also getting

> TypeError: Object #<ServerResponse> has no method 'local'
>     at /home/....../node_modules/express-form/lib/form.js:32:15

.. it's an obvious typo, if you look at few lines above and below that line (#32). Just add an "s" to the "res.local".

I'd like to see this fixed "officially", instead of modifying the package locally..

**Comment by freewil** [comment]
dup of #35
