### ISSUE TITLE
filter and validate do not work on certain field names

### ISSUE THREAD

**Issue by regisbamba** [dandean/express-form#4]
Hello, great plugin. I just have an issue.
if I have a field name such as
    account[owner][email]
I get the following error
    500 TypeError: Cannot call method 'replace' of undefined
    at [object Object].trim (/usr/local/lib/node/.npm/validator/0.1.7/package/lib/filter.js:47:26)
    at /usr/local/lib/node/.npm/express-form/0.5.1/package/lib/filter.js:29:36
    at /usr/local/lib/node/.npm/express-form/0.5.1/package/lib/filter.js:15:29
    at Array.forEach (native)
    at Filter.run (/usr/local/lib/node/.npm/express-form/0.5.1/package/lib/filter.js:14:11)
    at /usr/local/lib/node/.npm/express-form/0.5.1/package/lib/form.js:97:28
    at Array.forEach (native)
    at Object. (/usr/local/lib/node/.npm/express-form/0.5.1/package/lib/form.js:96:14)
    at param (/usr/local/lib/node/.npm/connect/0.5.10/package/lib/connect/middleware/router.js:146:21)
    at pass (/usr/local/lib/node/.npm/connect/0.5.10/package/lib/connect/middleware/router.js:162:10)

The error is due to the fact that in line 15 of filter.js you have
     formData[fieldname] = filter(formData[fieldname])

So in this case formData[fieldname] becomes
    formData[account[owner][email]]
wich in fact does not exist. The correct form should be
    formData[account][owner][email]

So somehow your function should be able to parse field names of the form "object[field]"

Thanks for the great work.

**Comment by dandean** [comment]
This is interesting -- I haven't tested with field names in that format yet. I'll look into getting a fix out as soon as I can, but it probably won't be for a few days, at least.

**Comment by wavded** [comment]
fyi, I put in a patch for this functionality.

**Comment by dandean** [comment]
Thanks for the patch wavdad!

rbamba -- this is now available as the latest version from npm.

**Comment by regisbamba** [comment]
Thank you very much.

**Comment by shamod** [comment]
run into this error. i have 

input(id="name", name="user[name]", type="text", value='') and it fails on filter 

form( filter( "user[name]" ).trim( ) )

with this error 

TypeError: Cannot call method 'replace' of undefined 

Using v0.5.3. Any idea?

**Comment by wavded** [comment]
possibly, now that I think of it, I just focused on validate, and not filter.

**Comment by dandean** [comment]
@shamod: I'll open an issue with your notes so I can track it. Thanks for the report!
