### ISSUE TITLE
Custom validation with asynchronous callback

### ISSUE THREAD

**Issue by nfedyashev** [dandean/express-form#5]
Hi Dan

First of all - thanks for a great tool!

If there is any way to perform custom validation using asynchronous callbacks?

Let's say I want to validate email/username uniqueness:

```
.custom(function(email) {
  User.find({}, function(err, user) {
    throw new Error("asynchronous validation failed");
  };
}
```

This would generate an error:

```
node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick

Error: asynchronous validation failed
    at /home/nikita/Sites/nodejs/kg-uploader/controllers/users.js:47:34
    at /home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/lib/mongoose/query.js:573:22
    at model.<anonymous> (/home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/lib/mongoose/document.js:141:5)
    at model.init (/home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/lib/mongoose/document.js:571:33)
    at /home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/lib/mongoose/query.js:571:16
    at /home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/support/node-mongodb-native/lib/mongodb/cursor.js:122:15
    at /home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/support/node-mongodb-native/lib/mongodb/cursor.js:163:11
    at /home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/support/node-mongodb-native/lib/mongodb/cursor.js:454:28
    at [object Object].close (/home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/support/node-mongodb-native/lib/mongodb/cursor.js:605:17)
    at [object Object].nextObject (/home/nikita/Sites/nodejs/kg-uploader/lib/mongoose/support/node-mongodb-native/lib/mongodb/cursor.js:454:10)
```

It looks like a common use case and many users may eventually face this problem
If there is any way to overcome it?

**Comment by dandean** [comment]
Hi Nikita,

I've been thinking about how best to deal with that scenario, but haven't come to a solution yet. I'm fairly certain I'll implement something, but it may involve API changes... we'll see. I'll keep this issue open until I implement that feature.

Thanks for the interest and the feedback!

**Comment by thomasleese** [comment]
I am just wondering, has a solution to this problem been found yet? And if not, is there a work around for doing this?

**Comment by bcharbonnier** [comment]
Hi there,

Is there any news about this one ?

**Comment by alanclarke** [comment]
actually this is not so hard, the way i solved it is as follows: https://gist.github.com/2588664

essentially you can have an async route middleware function before the form declaration that adds the data you need to req.body, which then gets passed to the custom validation function

**Comment by freewil** [comment]
Just implemented this in the latest fork: https://github.com/freewil/express-form/pull/4
