### ISSUE TITLE
isFloat fails on non-integer values

### ISSUE THREAD

**Issue by beaunus** [dandean/express-form#50]
https://github.com/dandean/express-form/blob/602899be11767f90559bc6beb20bf9a405695f4d/lib/field.js#L254

It seems that `isFloat` should have a valid response if the value is a numeric non-integer. For example: 4.5.

Perhaps the `isFloat` and `isDecimal` methods should be renamed to `isInt`.

If you'd like, I can propose a solution and submit a PR, but I'd like to know your thoughts about this.

Thank you.

**Comment by dandean** [comment]
The primary fork is now https://github.com/freewil/express-form
