### ISSUE TITLE
documentation inconsistency

### ISSUE THREAD

**Issue by wavded** [dandean/express-form#6]
<pre>
Validator.prototype.required = function(placeholderValue, message) {
  this.__required = true;
  return this.add(function(value) {
    if (!hasValue(value) || value == placeholderValue) {
      throw new Error(message || "%s is required");
    }
  });
};
</pre>

But in your documentation it states that the message is the first argument and there is no second.  BTW, great job, this is making life easier :)

**Comment by dandean** [comment]
Ah, damn. Sorry about that. I'll fix the docs as soon as I can.

**Comment by JanVanRyswyck** [comment]
Isn't it more clear to make 'placeholdervalue' the second parameter. That way you can have a custom message that doesn't need a placeholder value without the need for providing it as the first argument.

require('', 'My custom message')

vs 

require('My custom message')

**Comment by freewil** [comment]
This has since been resolved.
